#pragma once

#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD

#define COMBO_TERM 30
#define COMBO_SHOULD_TRIGGER

#define FORCE_NKRO

#define UNICODE_SELECTED_MODES UNICODE_MODE_MACOS

#ifdef MOUSEKEY_ENABLE
// The default is 100
#define MOUSEKEY_WHEEL_INTERVAL 50
// The default is 40
#define MOUSEKEY_WHEEL_TIME_TO_MAX 100
#endif